Update simudflix.yml

diff --git a/.github/workflows/simudflix.yml b/.github/workflows/simudflix.yml
--- a/.github/workflows/simudflix.yml
+++ b/.github/workflows/simudflix.yml
@@ -31,8 +31,12 @@ jobs:
 
     - name: Install ChromeDriver
       run: |
-        CHROME_VERSION=$(google-chrome --version | awk '{print $3}' | cut -d'.' -f1)
+        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+' | cut -d'.' -f1)
         CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION}")
+        if [ -z "$CHROMEDRIVER_VERSION" ]; then
+          echo "Error: Failed to retrieve ChromeDriver version."
+          exit 1
+        fi
         wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
         unzip chromedriver_linux64.zip
         sudo mv chromedriver /usr/local/bin/
